language: python

python:
  - 3.8

jobs:
  include:
    - stage: test
      name: analyse
      install:
        - pip install tox tox-factor
      script:
        - tox -f lint

    - stage: test
      name: unit tests
      install:
        # pinning coverage package until bugs with coveralls plugin is fixed
        # https://github.com/z4r/python-coveralls/issues/73
        - pip install tox tox-factor python-coveralls "coverage<5.0"
      script:
        - tox -f test
        - coveralls

    # Deploy to test.pypi.org for branches
    # Deploy to pypi.org for tags
    # NOTE: You can not replace builds published to pypi, even if you delete one
    #       so you must make sure your versions are always unique
    - stage: deploy
      name: deploy-release
      script:
        - pip install twine tox tox-factor
        - tox -f package
        - twine upload dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS
      if: tag IS true
    - stage: deploy
      name: deploy-snapshot
      script:
        - pip install twine tox tox-factor
        - tox -f package
        - twine upload --repository-url https://test.pypi.org/legacy/
            dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS
      if: tag IS NOT true
