"""Main entry point module for the application"""
import sys
import logging
from qtpy.QtWidgets import QApplication
from qtpy.QtCore import Qt
from friendlypics2.dialogs.main_window import MainWindow
from friendlypics2.version import __version__


def run(args):
    """Main entrypoint function

    Args:
        args (list): command line arguments to be passed to the application

    Returns:
        int: return code to report back to the shell with
    """
    logging.basicConfig(level=logging.DEBUG)

    # HACK: this next line was needed to silence an odd warning message generated by Qt
    QApplication.setAttribute(Qt.AA_ShareOpenGLContexts)

    # Configure our application
    app = QApplication(args)
    app.setOrganizationName("The Friendly Coder")
    app.setOrganizationDomain("https://github.com/TheFriendlyCoder")
    app.setApplicationName("FriendlyPics2")
    app.setApplicationVersion(__version__)

    # Configure our main window
    widget = MainWindow()
    widget.show()

    # Run our app
    return app.exec_()


if __name__ == "__main__":
    sys.exit(run(sys.argv))
